### ISSUE TITLE
Swift Package can only be added to one target

### ISSUE THREAD

**Issue by slickjam** [aws/amazon-chime-sdk-ios-spm#4]
In a project with multiple targets this swift package can only be added to one target. It doesn't show up when you try to add it to the Framework, Libraries, Embedded Content, under the General tab of the build target.

**Comment by pabloarista** [comment]
I'm having the same problem. I've been fighting with this since last night. At one point I thought it was related to the version number so I switched to using the branch with the release version, but that wasn't it. I do notice something different from all of the other packages is that the AmazonChimeSDK does NOT download the repo as the others. I'm thinking it could be that. I was trying to see what's different about the package.swift, but I am unfamiliar with it and they are all different.

![spm](https://github.com/aws/amazon-chime-sdk-ios-spm/assets/3964831/812ef023-1c9b-4513-91c3-a384f6078f2c)

**Comment by pabloarista** [comment]
I was able to add it. I had to manually add it, but for some reason Xcode doesn't show them in alphabetical order. They are in the order in which they were added. So you have to scroll all the way to the bottom.

**Comment by slickjam** [comment]
I don't see it listed and it doesn't come up in a search for Amazon or Chime. I can copy the target and it will be included but that is the only work around I've seen and I didn't check that it would compile if I did that.

**Comment by pabloarista** [comment]
Oh that's right. That happened to me too. What I did was this:
1. Closed Xcode
2. I removed AmazonChimeSDK from my pod file
3. Ran pod install
4. I opened up the project file
5. Deleted all lines that reference the amazonChimeSDK
6. Opened Xcode
7. cmd+shift+k to clean
8. Added the amazonChimeSDK swift package to major version 0.23.1
9. I opened up the 2nd target that requires the dependency
10. Manually added the swift package
    a. Here is when it finally showed up and I had to scroll down or search like you mentioned

I hope that helps. this was quite frustrating for me. It was the only dependency that had issues. At one point one other dependency was having issues because I added/removed/added/etc the amazon package so many times. I had to remove that 1 package and re-added like 2-3 times before it stopped acting up (on Xcode it was trying and trying to add it every time I restarted Xcode). it's really strange, but it's working now.

**Comment by slickjam** [comment]
@pabloarista - Are you sure the sdk was removed from the Pods folder?

**Comment by pabloarista** [comment]
yes. when you do pod install you should see a message on the terminal that says something like "uninstalling amazonchimesdk". If you still see it on Xcode. just close Xcode and then run pod install again. something could've been cached. you have to make sure it's no longer on the pods project. I think the problem is related to the references on the amayzonchimesdk on the project

**Comment by slickjam** [comment]
I never had it installed via CocoaPods. I still think it is something with the package at least for my project at this point.

**Comment by pabloarista** [comment]
oh my bad. I just assumed everyone was coming from cocoa pods. I'm in the process of migrating all of our dependencies from cocoa pods to swift package manager. I just deleted the local repo and did a git clone to confirm everything is good, so it is there and tested the app. Just having some weird issues on the test project, but it's a different issue. There is def something strange about this swift package

**Comment by slickjam** [comment]
No worries - It should have been a CocoaPod, but it was added as a framework directly. I was cleaning that up when I ran into this issue. The team doesn't want to use CocoaPods for some reason :(

I'd prefer SPM but CocoaPods is better than committed frameworks in my opinion. I tried the Chime package with a completely different project and had the same result.

I'm glad you got your issue resolved. I'm hoping the maintainers can shed some light on the issue if it is mine or an issue with the package.

**Comment by pabloarista** [comment]
Well hope you can resolve it soon

**Comment by slickjam** [comment]
@georgezy-amzn - Any help you can provide? Thanks in advance.

**Comment by georgezy-amzn** [comment]
Not sure if this is hacky: right click on the target with SPM dependencies, select `duplicate`, the duplicated target contains the SPM dependencies.

**Comment by slickjam** [comment]
It is a bit hacky :)  but I did try it and it did seem to work. Unfortunately it isn't a good solution for me because there are 10 different build targets to my team's project so duplicating one working on then trying to recreate all the build targets is a very large task filled with a lot of risk.

**Comment by georgezy-amzn** [comment]
In this case you should also be able to add them by manually edit `project.pbxproj`.

**Comment by slickjam** [comment]
Thanks - I appreciate the quick response.
